// Galaxy Runner - in-game help content
// Pause-screen game information lives here so UI code does not hardcode design text.

const GAME_INFO_CONFIG = Object.freeze({
  button: Object.freeze({
    x: 774,
    y: 58,
    width: 86,
    height: 30,
    radius: 12,
    label: "게임 정보",
  }),
  panel: Object.freeze({
    x: 60,
    y: 36,
    width: 840,
    height: 466,
    radius: 18,
    titleY: 70,
    titleFont: "800 26px Segoe UI, Noto Sans KR, sans-serif",
    sectionFont: "800 13px Segoe UI, Noto Sans KR, sans-serif",
    bodyFont: "700 11px Segoe UI, Noto Sans KR, sans-serif",
    hintFont: "600 12px Segoe UI, Noto Sans KR, sans-serif",
    titleColor: "#f6fbff",
    sectionColor: "#9af8ff",
    bodyColor: "rgba(239, 250, 255, 0.84)",
    hintColor: "rgba(239, 250, 255, 0.58)",
    background: "rgba(5, 9, 18, 0.92)",
    border: "rgba(154, 248, 255, 0.36)",
  }),
  shipCards: Object.freeze({
    x: 88,
    y: 96,
    width: 190,
    height: 188,
    gap: 12,
    previewY: 78,
    previewSize: 82,
    titleY: 24,
    tagStartY: 126,
    tagGap: 21,
    tagHeight: 17,
    cardBackground: "rgba(8, 17, 31, 0.74)",
    cardBorder: "rgba(154, 248, 255, 0.22)",
  }),
  itemGrid: Object.freeze({
    titleX: 88,
    titleY: 318,
    x: 88,
    y: 338,
    columns: 4,
    width: 190,
    height: 52,
    gapX: 12,
    gapY: 10,
    iconX: 26,
    iconY: 26,
    iconSize: 30,
    textX: 48,
    nameY: 20,
    effectY: 37,
    cardBackground: "rgba(8, 17, 31, 0.66)",
    cardBorder: "rgba(255, 255, 255, 0.11)",
  }),
});

const GAME_INFO = Object.freeze({
  title: "게임 정보",
  hint: "Esc: 게임 재개 / 게임 정보 버튼 다시 클릭: 닫기",
  ships: Object.freeze([
    Object.freeze({
      kind: "rapid",
      name: "Rapid",
      color: "#ffe06a",
      tags: Object.freeze(["속도++", "피격 80%", "추적 관통빔"]),
    }),
    Object.freeze({
      kind: "energy",
      name: "Energy",
      color: "#9af8ff",
      tags: Object.freeze(["중장갑", "탄 흡수", "보호막 코어"]),
    }),
    Object.freeze({
      kind: "spread",
      name: "Spread",
      color: "#b7ff7b",
      tags: Object.freeze(["광역", "다중탄", "산탄 폭풍"]),
    }),
    Object.freeze({
      kind: "nova",
      name: "Nova",
      color: "#ff8f5a",
      tags: Object.freeze(["중장갑", "폭발 성장", "방어 지뢰"]),
    }),
  ]),
  items: Object.freeze([
    Object.freeze({ kind: "repair", name: "수리", color: "#ff6f8f", effect: "HP 회복" }),
    Object.freeze({ kind: "armor", name: "장갑", color: "#d8e6f0", effect: "최대 HP+" }),
    Object.freeze({ kind: "shield", name: "실드", color: "#75dfff", effect: "실드 +10" }),
    Object.freeze({ kind: "shieldDefense", name: "실드 방어", color: "#9af8ff", effect: "피해 -0.5" }),
    Object.freeze({ kind: "rapid", name: "무기", color: "#ffe06a", effect: "최고 LV 복귀" }),
    Object.freeze({ kind: "weaponCore", name: "코어", color: "#f6fbff", effect: "10LV 후 +5%" }),
    Object.freeze({ kind: "drone", name: "드론", color: "#b4a2ff", effect: "보조 공격" }),
    Object.freeze({ kind: "bonus", name: "오버드라이브", color: "#ff92c9", effect: "100% 6초" }),
  ]),
});
