// Galaxy Runner - runtime configuration
// Business and presentation code should read named values from here instead of carrying magic numbers.

const GAME_CONFIG = Object.freeze({
  dprFallback: 1,
  maxFrameDelta: 0.04,
  initialState: Object.freeze({
    mode: "ready",
    time: 0,
    distance: 0,
    score: 0,
    kills: 0,
    continues: 0,
    stage: 1,
    spawnTimer: -0.9,
    itemTimer: 2.2,
    spawnInterval: 1.25,
    itemInterval: 5.4,
    nextMidBoss: 42,
    nextBoss: 105,
    danger: 0,
  }),
  scoring: Object.freeze({
    distancePerSecond: 42,
    enemyDangerMultiplierPerLevel: 0.08,
    enemyRoleScore: Object.freeze({
      scout: 80,
      fighter: 120,
      striker: 150,
      tank: 260,
      raider: 140,
      sniper: 320,
      splitter: 260,
      guardian: 360,
      midboss: 650,
      boss: 2000,
      fallback: 120,
    }),
  }),
  enemyDestruction: Object.freeze({
    eliteHealthThreshold: 1,
    normalBurstCount: 10,
    eliteBurstCount: 18,
  }),
  danger: Object.freeze({
    max: 18,
    secondsPerDanger: 22,
  }),
  spawn: Object.freeze({
    intervalBase: 1.25,
    intervalMin: 0.46,
    intervalDangerStep: 0.045,
    extraOneDangerStart: 3,
    extraOneChanceStep: 0.045,
    extraOneChanceMax: 0.42,
    extraTwoDangerStart: 9,
    extraTwoChanceStep: 0.025,
    extraTwoChanceMax: 0.24,
    lateralStartTime: 18,
    lateralChanceBase: 0.04,
    lateralChanceDangerStep: 0.013,
    lateralChanceMax: 0.24,
  }),
  items: Object.freeze({
    intervalBase: 5.4,
    intervalMin: 4.1,
    intervalDangerStep: 0.045,
    maxOnField: 4,
  }),
  bosses: Object.freeze({
    midBossRepeatDelay: 58,
    bossRepeatDelay: 130,
    midBossBossGap: 28,
    midBossAfterBossDelay: 45,
    nextMidBossAfterBossMinDelay: 60,
  }),
  projectiles: Object.freeze({
    enemyHitPlayerRadiusScale: 0.72,
  }),
  continue: Object.freeze({
    mode: "running",
    playerInvincibility: 2.4,
    spawnGraceSeconds: 1.2,
    itemGraceSeconds: 1.2,
  }),
});

const INPUT_CONFIG = Object.freeze({
  preventDefaultCodes: Object.freeze([
    "Space",
    "ControlLeft",
    "ControlRight",
    "ArrowUp",
    "ArrowDown",
    "ArrowLeft",
    "ArrowRight",
    "KeyW",
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyP",
    "KeyR",
    "Escape",
  ]),
  pauseCodes: Object.freeze(["KeyP", "Escape"]),
  startCode: "Space",
  restartCode: "KeyR",
});

const PLAYER_CONFIG = Object.freeze({
  assets: Object.freeze({
    parts: Object.freeze({ src: "assets/player/player-registered-parts-v1.png", columns: 4, rows: 3 }),
    weaponEvolution: Object.freeze({ src: "assets/player/player-weapon-part-states-v5.png", columns: 10, rows: 4 }),
    thruster: Object.freeze({ src: "assets/player/thruster-registered-v1.png", columns: 4, rows: 3 }),
    specialEffect: Object.freeze({ src: "assets/player/special-effects-registered-v1.png", columns: 4, rows: 4 }),
  }),
  basePosition: Object.freeze({
    xRatio: 0.5,
    yFromBottom: 72,
  }),
  radii: Object.freeze({
    body: 11,
    hit: 13,
    pickup: 20,
  }),
  visual: Object.freeze({
    scale: 0.56,
    hitboxPadding: 5.4,
    invincibleBlinkRate: 18,
    invincibleAlpha: 0.42,
  }),
  movement: Object.freeze({
    speed: 240,
    bounds: Object.freeze({
      left: 32,
      rightPadding: 32,
      top: 42,
      bottomPadding: 36,
    }),
    leanMax: 0.42,
    thrust: Object.freeze({
      base: 1,
      upBoost: 0.72,
      downPenalty: -0.42,
      sideBoost: 0.12,
      min: 0.52,
      max: 1.85,
      ease: 9,
    }),
  }),
  bank: Object.freeze({
    xScalePerLean: 0.16,
    yScalePerLean: 0.035,
    skewPerLean: -0.045,
    xOffsetPerLean: 3,
  }),
  fire: Object.freeze({
    yOffset: 18,
    spreadDelay: 0.24,
    spreadSideOffset: 6,
    spreadYOffset: 12,
    spreadRadius: 4,
  }),
  invincibility: Object.freeze({
    shieldAbsorb: 0.35,
    healthHit: 1.3,
  }),
  drone: Object.freeze({
    orbitRadiusX: 104,
    orbitRadiusY: 58,
    orbitSpeed: 2.7,
    initialAngle: -Math.PI / 2,
    directShotSpeed: 650,
    homingTurnRate: 9.5,
    homingLife: 3,
    homingRadius: 3.8,
    straightRadius: 3.5,
    shotYOffsetHoming: 8,
    shotYOffsetStraight: 12,
    color: "#aefcff",
    visualPulseBase: 0.7,
    visualPulseAmplitude: 0.08,
    visualPulseSpeed: 7,
    visualRotationWobbleSpeed: 4,
    visualRotationWobbleAmount: 0.12,
    visualRingAlphaBase: 0.8,
    visualRingWidthBase: 0.8,
    visualRingWidthLevelStep: 0.14,
    visualRingWidthUpgradeStep: 0.1,
    visualRingRadiusXBase: 9,
    visualRingRadiusXLevelStep: 1.5,
    visualRingRadiusXUpgradeStep: 0.75,
    visualRingRadiusYBase: 6,
    visualRingRadiusYLevelStep: 1,
    visualRingRadiusYUpgradeStep: 0.5,
    partWidthBase: 21,
    partWidthLevelStep: 4,
    partHeightBase: 19,
    partHeightLevelStep: 3.5,
  }),
  thruster: Object.freeze({
    highRow: 1,
    normalRow: 0,
    lowRow: 2,
    highThreshold: 1.13,
    lowThreshold: 0.86,
    frameRate: 18,
    alphaBase: 0.72,
    alphaScale: 0.18,
    alphaMin: 0.62,
    alphaMax: 1.08,
    shadowColor: "rgba(255, 139, 47, 0.7)",
    shadowBlur: 10,
  }),
});

const PLAYER_LAYOUT_CONFIG = Object.freeze({
  defaultRigSize: 250,
  partDefinitions: Object.freeze({
    fuselage: Object.freeze({ col: 0, row: 0 }),
    wings: Object.freeze({ col: 1, row: 0 }),
    engine: Object.freeze({ col: 2, row: 0 }),
    cockpit: Object.freeze({ col: 3, row: 0 }),
    armor: Object.freeze({ col: 0, row: 2 }),
    drone: Object.freeze({ col: 1, row: 2 }),
  }),
  droneScaleBase: 1,
  droneScaleLevelMin: 1,
  droneScaleLevelMax: 3,
  droneScaleLevelStep: 0.08,
});

const HUD_CONFIG = Object.freeze({
  topBarHeight: 74,
  background: "rgba(4, 8, 15, 0.42)",
  textColor: "#e9f8ff",
  hpX: 20,
  hpTextY: 18,
  healthBarY: 26,
  shieldBarY: 33,
  barWidth: 112,
  healthBarHeight: 5,
  shieldBarHeight: 3,
  scoreY: 18,
  stageX: 548,
  killX: 610,
  distanceX: 690,
  scoreX: 800,
  continueX: 610,
  continueY: 36,
  special: Object.freeze({
    iconX: 384,
    iconY: 22,
    iconSize: 24,
    valueX: 410,
    valueY: 20,
    barX: 408,
    barY: 28,
    barWidth: 168,
    barHeight: 8,
    borderColor: "rgba(255, 146, 201, 0.62)",
    fillColor: "#ff92c9",
    backColor: "rgba(10, 18, 30, 0.82)",
  }),
  statusGrid: Object.freeze({
    x: 20,
    y: 56,
    columns: 10,
    cellWidth: 84,
    iconSize: 22,
    iconXOffset: 10,
    valueXOffset: 27,
    valueYOffset: 4,
  }),
  mainFont: "800 12px Segoe UI, Noto Sans KR, sans-serif",
  tagFont: "700 11px Segoe UI, Noto Sans KR, sans-serif",
  healthColors: Object.freeze({
    high: "#75ffb8",
    medium: "#ffe06a",
    low: "#ff6f8f",
    highThreshold: 0.5,
    mediumThreshold: 0.25,
  }),
});

const ITEM_ICON_CONFIG = Object.freeze({
  defaultSize: 28,
  vectorBaseSize: 36,
  pickupRadiusScale: 1.55,
  imagePadding: 1,
});

const ITEM_FIELD_CONFIG = Object.freeze({
  spawn: Object.freeze({
    xPadding: 70,
    yMin: 72,
    yMax: 132,
  }),
  velocity: Object.freeze({
    xMin: -110,
    xMax: 110,
    yMin: 68,
    yMax: 122,
    bounceRetain: 1,
  }),
  bounds: Object.freeze({
    padding: 22,
  }),
  lifetime: 14,
  pulseSpeed: 5.4,
  morph: Object.freeze({
    intervalMin: 3.4,
    intervalMax: 5.2,
  }),
  blink: Object.freeze({
    startRemaining: 4,
    minRate: 4,
    maxRate: 18,
    visibleThreshold: -0.08,
  }),
  visual: Object.freeze({
    haloAlpha: 0.22,
    haloPadding: 5,
    haloPulse: 3,
    boxScale: 2,
    cornerRadiusMin: 6,
    cornerRadiusScale: 0.42,
    boxFill: "rgba(4, 9, 16, 0.82)",
    borderWidth: 3,
  }),
});

const ENEMY_CONFIG = Object.freeze({
  atlas: Object.freeze({
    src: "assets/enemies/enemy-ships-v1.png",
    columns: 3,
    rows: 2,
  }),
  picker: Object.freeze({
    scoutBaseChance: 0.28,
    scoutDangerStep: 0.01,
    scoutMinChance: 0.12,
    fighterChance: 0.3,
    strikerBaseChance: 0.22,
    strikerDangerStep: 0.008,
    strikerMinChance: 0.22,
    strikerMaxChance: 0.33,
    advancedStartDanger: 3,
    advancedChanceStep: 0.018,
    advancedChanceMax: 0.22,
    advancedRoles: Object.freeze(["sniper", "splitter", "guardian"]),
  }),
  health: Object.freeze({
    minimum: 1,
    nonBossDangerScale: 0.055,
  }),
  bullet: Object.freeze({
    levelDangerDivisor: 7,
    maxLevel: 4,
    spawnYOffsetRatio: 0.42,
    radius: 6,
    speedBase: 165,
    speedDangerStep: 11,
    speedMax: 340,
    color: "#ffca61",
    life: 4.5,
  }),
  setupFireCooldown: Object.freeze({
    minScale: 0.58,
    dangerStep: 0.028,
    initialMin: 0.55,
    initialMax: 1.35,
    nonShooterTimer: 99,
  }),
  firingWindow: Object.freeze({
    top: 20,
    bottomPadding: 120,
  }),
  escape: Object.freeze({
    padding: 70,
    raiderWidthMultiplier: 2,
  }),
  bossPattern: Object.freeze({
    forwardDegrees: 90,
    bossSpreadAngles: Object.freeze([-32, -16, 16, 32]),
    midBossSpreadAngles: Object.freeze([-22, 22]),
    bossSpeed: 205,
    midBossSpeed: 185,
    bossRadius: 7,
    midBossRadius: 6,
    bossBulletLevel: 3,
    midBossBulletLevel: 2,
    spawnYOffsetRatio: 0.32,
    bossColor: "#ff7f9b",
    midBossColor: "#ffd36c",
    life: 4.8,
  }),
  sniper: Object.freeze({
    chargeTime: 0.78,
    warningLineWidth: 2,
    warningColor: "rgba(255, 72, 92, 0.62)",
    shotSpeed: 520,
    shotRadius: 5.2,
    shotLevel: 3,
    shotLife: 2.6,
    shotColor: "#ff4a5c",
  }),
  guardian: Object.freeze({
    shieldHealthScale: 2.4,
    shieldRadiusScale: 1.34,
    shieldColor: "rgba(154, 248, 255, 0.38)",
    shieldHitBurst: 6,
  }),
  splitter: Object.freeze({
    childCount: 2,
    childRole: "scout",
    childXSpread: 26,
    childYSpread: 10,
    childBurst: 8,
  }),
  stageBoss: Object.freeze({
    armorPanelSrc: "assets/bosses/stage-boss-armor-panel.svg",
    armorPanelDamagedSrc: "assets/bosses/stage-boss-armor-panel-damaged.svg",
    coreSrcByStage: Object.freeze({
      1: "assets/bosses/stage-boss-core-1.svg",
      2: "assets/bosses/stage-boss-core-2.svg",
      3: "assets/bosses/stage-boss-core-3.svg",
    }),
    phase: Object.freeze({
      closed: 1.7,
      opening: 0.55,
      focus: 2.25,
      closing: 0.5,
    }),
    armor: Object.freeze({
      closedOffsetX: 38,
      openOffsetX: 91,
      offsetY: 2,
      width: 88,
      height: 132,
      damagedHealthRatio: 0.42,
    }),
    core: Object.freeze({
      width: 72,
      height: 82,
      glowRadius: 54,
    }),
    focusWarning: Object.freeze({
      lineWidth: 4,
      alpha: 0.52,
    }),
    stages: Object.freeze([
      Object.freeze({
        stage: 1,
        name: "Aegis Gate",
        color: "#ff617f",
        healthMultiplier: 1.22,
        fireDelay: 0.5,
        attack: "focus",
        scoreMultiplier: 1,
      }),
      Object.freeze({
        stage: 2,
        name: "Prism Lancer",
        color: "#ff92c9",
        healthMultiplier: 1.42,
        fireDelay: 0.72,
        attack: "lance",
        scoreMultiplier: 1.35,
      }),
      Object.freeze({
        stage: 3,
        name: "Brood Forge",
        color: "#ffb35b",
        healthMultiplier: 1.62,
        fireDelay: 0.62,
        attack: "summon",
        scoreMultiplier: 1.75,
      }),
    ]),
  }),
  movement: Object.freeze({
    waveSpeed: 2.4,
    bossPhaseSwaySpeed: 1.6,
    bossPhaseSwayAmount: 34,
    strikerSway: 58,
    scoutSway: 34,
    defaultSway: 26,
    raiderSway: 18,
    bossSideLimitRatio: 0.48,
    defaultSideLimit: 34,
  }),
  fireDelay: Object.freeze({
    dangerStep: 0.026,
    minScale: 0.52,
    boss: Object.freeze({ min: 0.68, max: 1.02 }),
    midboss: Object.freeze({ min: 0.82, max: 1.2 }),
    raider: Object.freeze({ min: 0.72, max: 1.18 }),
    sniper: Object.freeze({ min: 2.2, max: 3.2 }),
    guardian: Object.freeze({ min: 1.4, max: 2.2 }),
    splitter: Object.freeze({ min: 1.1, max: 1.8 }),
    default: Object.freeze({ min: 1.08, max: 1.95 }),
  }),
  visual: Object.freeze({
    defaultPadding: 2.5,
    bossWidthPadding: 2.48,
    tankWidthPadding: 2.42,
    bossHeightPadding: 2.42,
    raiderHeightPadding: 2.45,
    healthBarMinOffset: 8,
    healthBarOffsetRatio: 0.08,
    healthBarWidthHitboxRatio: 2.25,
    healthBarWidthVisualRatio: 0.66,
  }),
  roles: Object.freeze({
    scout: Object.freeze({
      width: 28,
      height: 28,
      hitRx: 11,
      hitRy: 12,
      health: () => 1,
      velocityX: () => randomRange(-72, 72),
      velocityY: (danger) => randomRange(110, 158) + danger * 5,
      color: "#7ef5ff",
      shooter: false,
      score: 70,
    }),
    fighter: Object.freeze({
      width: 38,
      height: 34,
      hitRx: 16,
      hitRy: 15,
      health: () => 2,
      velocityX: () => randomRange(-44, 44),
      velocityY: (danger) => randomRange(78, 124) + danger * 4,
      color: "#ff6f9c",
      shooter: true,
      bulletLevel: 1,
      score: 110,
    }),
    striker: Object.freeze({
      width: 46,
      height: 32,
      hitRx: 20,
      hitRy: 13,
      health: () => 2,
      velocityX: () => randomRange(-28, 28),
      velocityY: (danger) => randomRange(88, 132) + danger * 4,
      color: "#b7ff7b",
      shooter: true,
      bulletLevel: 1,
      score: 130,
    }),
    tank: Object.freeze({
      width: 58,
      height: 46,
      hitRx: 24,
      hitRy: 18,
      health: () => 5,
      velocityX: () => randomRange(-24, 24),
      velocityY: (danger) => randomRange(54, 84) + danger * 3,
      color: "#ffb35b",
      shooter: true,
      bulletLevel: 2,
      score: 220,
    }),
    raider: Object.freeze({
      width: 44,
      height: 30,
      hitRx: 19,
      hitRy: 13,
      health: () => 3,
      velocityX: (danger) => 190 + danger * 9,
      velocityY: (danger) => randomRange(10, 30) + danger * 1.4,
      color: "#a58cff",
      shooter: true,
      bulletLevel: 1,
      score: 180,
    }),
    sniper: Object.freeze({
      width: 48,
      height: 36,
      hitRx: 19,
      hitRy: 14,
      health: () => 5,
      velocityX: () => randomRange(-18, 18),
      velocityY: (danger) => randomRange(38, 62) + danger * 2.2,
      color: "#ff4a5c",
      shooter: true,
      bulletLevel: 3,
      score: 320,
    }),
    splitter: Object.freeze({
      width: 52,
      height: 38,
      hitRx: 21,
      hitRy: 15,
      health: () => 6,
      velocityX: () => randomRange(-34, 34),
      velocityY: (danger) => randomRange(58, 88) + danger * 2.8,
      color: "#d58cff",
      shooter: true,
      bulletLevel: 2,
      score: 260,
    }),
    guardian: Object.freeze({
      width: 64,
      height: 48,
      hitRx: 27,
      hitRy: 20,
      health: () => 7,
      velocityX: () => randomRange(-20, 20),
      velocityY: (danger) => randomRange(42, 68) + danger * 2.2,
      color: "#75dfff",
      shooter: true,
      bulletLevel: 2,
      score: 360,
    }),
    midboss: Object.freeze({
      width: 122,
      height: 76,
      hitRx: 50,
      hitRy: 30,
      health: (danger) => 46 + danger * 4,
      velocityX: () => 70,
      velocityY: () => 54,
      color: "#ffcf67",
      shooter: true,
      bulletLevel: 2,
      score: 1200,
    }),
    boss: Object.freeze({
      width: 178,
      height: 108,
      hitRx: 72,
      hitRy: 42,
      health: (danger) => 138 + danger * 9,
      velocityX: () => 54,
      velocityY: () => 38,
      color: "#ff617f",
      shooter: true,
      bulletLevel: 3,
      score: 4200,
    }),
  }),
  spawn: Object.freeze({
    xPadding: 52,
    gruntY: -70,
    midBossY: -100,
    bossY: -130,
    bossXRatio: 0.5,
    bossStopY: 86,
    midBossStopY: 96,
    raiderYMin: 72,
    raiderYMaxRatio: 0.46,
  }),
  spriteCells: Object.freeze({
    scout: Object.freeze([0, 0]),
    fighter: Object.freeze([1, 0]),
    striker: Object.freeze([2, 0]),
    raider: Object.freeze([2, 0]),
    tank: Object.freeze([0, 1]),
    midboss: Object.freeze([1, 1]),
    boss: Object.freeze([2, 1]),
  }),
});

const PROJECTILE_CONFIG = Object.freeze({
  atlas: Object.freeze({
    src: "assets/projectiles/projectiles-v1.png",
    columns: 4,
    rows: 2,
  }),
  defaults: Object.freeze({
    damage: BALANCE.statScale,
    kind: "bolt",
    hostile: false,
    level: 1,
    absorbLevel: 0,
    life: 2.4,
    homing: false,
    turnRate: 8,
    pierce: 0,
    blastRadius: 0,
    beamWidth: 0,
    beamLength: 0,
    followPlayer: false,
    minimumHomingSpeed: 1,
  }),
  hitIntervals: Object.freeze({
    rapidBeam: 0.075,
    energy: 0.16,
    default: 999,
  }),
  hitRadius: Object.freeze({
    hostile: 0.82,
    rapidMinimum: 2.4,
    rapid: 0.9,
    energy: 0.95,
    nova: 0.95,
    drone: 1.05,
  }),
  expiry: Object.freeze({
    padding: 60,
  }),
  rapidBeam: Object.freeze({
    followLengthPadding: 96,
  }),
  energyCoreVisual: Object.freeze({
    shellRadius: 1.42,
    innerRadius: 0.46,
    ringRadius: 1.78,
    ringSquash: 0.34,
    haloRadius: 2.35,
    pulseSpeed: 0.009,
    pulseAmount: 0.13,
    spokeCount: 6,
    spokeInnerRadius: 0.58,
    spokeOuterRadius: 1.42,
    absorbedPulsePerBullet: 0.018,
    absorbedPulseMax: 0.28,
    shieldArcLineWidth: 2.4,
    coreLineWidth: 1.6,
  }),
  spriteScales: Object.freeze({
    hostileLevel3: 5.6,
    hostileLevel2: 4.9,
    hostileLevel1: 4.55,
    bolt: Object.freeze({ width: 3.2, height: 10.4 }),
    rapid: Object.freeze({ width: 4.1, height: 15.2 }),
    energy: Object.freeze({ width: 5.8, height: 5.8 }),
    spread: Object.freeze({ width: 3.2, height: 9.4 }),
    nova: Object.freeze({ width: 6.2, height: 6.2 }),
    drone: Object.freeze({ width: 5.2, height: 9.6 }),
  }),
  spriteCells: Object.freeze({
    hostileBasic: Object.freeze({ col: 2, row: 1 }),
    hostileAdvanced: Object.freeze({ col: 3, row: 1 }),
    bolt: Object.freeze({ col: 0, row: 0 }),
    rapid: Object.freeze({ col: 1, row: 0 }),
    energy: Object.freeze({ col: 2, row: 0 }),
    spread: Object.freeze({ col: 3, row: 0 }),
    nova: Object.freeze({ col: 0, row: 1 }),
    drone: Object.freeze({ col: 1, row: 1 }),
  }),
});

const BACKGROUND_CONFIG = Object.freeze({
  starCount: 150,
  starRadius: Object.freeze({ min: 0.7, max: 2.4 }),
  starSpeed: Object.freeze({ min: 35, max: 190 }),
  starAlpha: Object.freeze({ min: 0.22, max: 0.9 }),
  resetPadding: 8,
  gradient: Object.freeze({
    top: "#07152c",
    middle: "#080b1a",
    middleStop: 0.48,
    bottom: "#141113",
  }),
  nebula: Object.freeze({
    alpha: 0.22,
    count: 5,
    speedBase: 34,
    speedStep: 11,
    yOffsetStep: 145,
    heightPadding: 180,
    startYOffset: 90,
    colorA: "#ffb66c",
    colorB: "#79dfff",
    lineWidth: 2,
  }),
});

const BURST_CONFIG = Object.freeze({
  speed: Object.freeze({ min: 50, max: 180 }),
  radius: Object.freeze({ min: 2, max: 5 }),
  life: Object.freeze({ min: 0.32, max: 0.72 }),
  alphaMultiplier: 1.8,
});

const DRONE_CONFIG = Object.freeze({
  maxLevel: 12,
  maxCount: 3,
  baseFireInterval: 1.05,
  earlyLevelMax: 3,
  levelOneRateDivisor: 2,
  upgradesPerCycle: 3,
  upgradeRateMultiplier: 1.5,
  highDamageLevel: 10,
  baseDamageMultiplier: 1,
  highDamageMultiplier: 2,
});

const SPECIAL_CONFIG = Object.freeze({
  meterMax: 100,
  passiveRegenPerSecond: 0.8,
  inputCodes: Object.freeze(["ControlLeft", "ControlRight"]),
  tierCosts: Object.freeze([75, 50, 25]),
  overdrive: Object.freeze({
    duration: 6,
  }),
  killGain: Object.freeze({
    base: 2,
    perThreatLevel: 2,
    midBossBonus: 14,
    bossBonus: 30,
  }),
  readyEffect: Object.freeze({
    frameRate: 12,
    alphaMin: 0.12,
    alphaMax: 0.36,
    shadowAlpha: 0.46,
    shadowBlur: 7,
  }),
  rapid: Object.freeze({
    color: "#ffe06a",
    beamLengthPadding: 96,
    hitInterval: 0.075,
    levelDamageStep: 0.12,
    tiers: Object.freeze({
      25: Object.freeze({ width: 26, duration: 0.34, damageScale: 2.4, burst: 12 }),
      50: Object.freeze({ width: 42, duration: 0.52, damageScale: 4.2, burst: 20 }),
      75: Object.freeze({ width: 62, duration: 0.76, damageScale: 6.8, burst: 30 }),
    }),
  }),
  energy: Object.freeze({
    color: "#9af8ff",
    yOffset: 24,
    levelDamageStep: 0.16,
    tiers: Object.freeze({
      25: Object.freeze({
        radius: 22,
        speed: -120,
        damageScale: 2.2,
        hitInterval: 0.24,
        absorbLevel: 2,
        life: 3.4,
        releaseRadius: 84,
        releaseDamageScale: 0.32,
        releaseBurst: 18,
        releaseHitBurst: 5,
        burst: 14,
      }),
      50: Object.freeze({
        radius: 34,
        speed: -85,
        damageScale: 3.7,
        hitInterval: 0.2,
        absorbLevel: 3,
        life: 4.4,
        releaseRadius: 126,
        releaseDamageScale: 0.42,
        releaseBurst: 28,
        releaseHitBurst: 7,
        burst: 22,
      }),
      75: Object.freeze({
        radius: 48,
        speed: -55,
        damageScale: 5.6,
        hitInterval: 0.16,
        absorbLevel: 4,
        life: 5.6,
        releaseRadius: 176,
        releaseDamageScale: 0.52,
        releaseBurst: 40,
        releaseHitBurst: 9,
        burst: 32,
      }),
    }),
  }),
  spread: Object.freeze({
    color: "#b7ff7b",
    yOffset: 18,
    levelDamageStep: 0.08,
    tiers: Object.freeze({
      25: Object.freeze({ shots: 10, span: 88, speed: 340, radius: 4.4, damageScale: 1.25, pierce: 0, life: 2.0, burst: 16 }),
      50: Object.freeze({ shots: 18, span: 128, speed: 370, radius: 4.9, damageScale: 1.65, pierce: 1, life: 2.25, burst: 24 }),
      75: Object.freeze({ shots: 30, span: 170, speed: 410, radius: 5.4, damageScale: 2.1, pierce: 2, life: 2.55, burst: 36 }),
    }),
  }),
  nova: Object.freeze({
    mineKind: "novaMine",
    cost: 20,
    maxMines: 5,
    color: "#ffb176",
    yOffset: 18,
    radius: 24,
    speed: 0,
    life: Infinity,
    damageScale: 2.6,
    blastRadiusScale: 3.2,
    blastDurationScale: 1.15,
    burst: 16,
    visual: Object.freeze({
      pulseSpeed: 0.012,
      pulseAmount: 0.12,
      glowRadius: 1.85,
      ringRadius: 1.45,
      coreRadius: 0.56,
      spokeCount: 6,
      blastPreviewAlpha: 0.18,
      blastPreviewLineWidth: 2,
    }),
  }),
});
